// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: marketData.proto

package contracts_marketdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MarketData_GetCandles_FullMethodName         = "/marketData.MarketData/GetCandles"
	MarketData_SubscribeCandles_FullMethodName   = "/marketData.MarketData/SubscribeCandles"
	MarketData_SubscribeOrders_FullMethodName    = "/marketData.MarketData/SubscribeOrders"
	MarketData_SubscribeOrderbook_FullMethodName = "/marketData.MarketData/SubscribeOrderbook"
)

// MarketDataClient is the client API for MarketData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketDataClient interface {
	// Название нашего эндпоинта
	GetCandles(ctx context.Context, in *GetCandlesRequest, opts ...grpc.CallOption) (*GetCandlesResponse, error)
	SubscribeCandles(ctx context.Context, in *SubscribeCandlesRequest, opts ...grpc.CallOption) (MarketData_SubscribeCandlesClient, error)
	SubscribeOrders(ctx context.Context, in *SubscribeOrderRequest, opts ...grpc.CallOption) (MarketData_SubscribeOrdersClient, error)
	SubscribeOrderbook(ctx context.Context, in *SubscribeOrderbookRequest, opts ...grpc.CallOption) (MarketData_SubscribeOrderbookClient, error)
}

type marketDataClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataClient(cc grpc.ClientConnInterface) MarketDataClient {
	return &marketDataClient{cc}
}

func (c *marketDataClient) GetCandles(ctx context.Context, in *GetCandlesRequest, opts ...grpc.CallOption) (*GetCandlesResponse, error) {
	out := new(GetCandlesResponse)
	err := c.cc.Invoke(ctx, MarketData_GetCandles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataClient) SubscribeCandles(ctx context.Context, in *SubscribeCandlesRequest, opts ...grpc.CallOption) (MarketData_SubscribeCandlesClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[0], MarketData_SubscribeCandles_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &marketDataSubscribeCandlesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketData_SubscribeCandlesClient interface {
	Recv() (*OHLC, error)
	grpc.ClientStream
}

type marketDataSubscribeCandlesClient struct {
	grpc.ClientStream
}

func (x *marketDataSubscribeCandlesClient) Recv() (*OHLC, error) {
	m := new(OHLC)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketDataClient) SubscribeOrders(ctx context.Context, in *SubscribeOrderRequest, opts ...grpc.CallOption) (MarketData_SubscribeOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[1], MarketData_SubscribeOrders_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &marketDataSubscribeOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketData_SubscribeOrdersClient interface {
	Recv() (*OrderState, error)
	grpc.ClientStream
}

type marketDataSubscribeOrdersClient struct {
	grpc.ClientStream
}

func (x *marketDataSubscribeOrdersClient) Recv() (*OrderState, error) {
	m := new(OrderState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketDataClient) SubscribeOrderbook(ctx context.Context, in *SubscribeOrderbookRequest, opts ...grpc.CallOption) (MarketData_SubscribeOrderbookClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[2], MarketData_SubscribeOrderbook_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &marketDataSubscribeOrderbookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketData_SubscribeOrderbookClient interface {
	Recv() (*Orderbook, error)
	grpc.ClientStream
}

type marketDataSubscribeOrderbookClient struct {
	grpc.ClientStream
}

func (x *marketDataSubscribeOrderbookClient) Recv() (*Orderbook, error) {
	m := new(Orderbook)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MarketDataServer is the server API for MarketData service.
// All implementations must embed UnimplementedMarketDataServer
// for forward compatibility
type MarketDataServer interface {
	// Название нашего эндпоинта
	GetCandles(context.Context, *GetCandlesRequest) (*GetCandlesResponse, error)
	SubscribeCandles(*SubscribeCandlesRequest, MarketData_SubscribeCandlesServer) error
	SubscribeOrders(*SubscribeOrderRequest, MarketData_SubscribeOrdersServer) error
	SubscribeOrderbook(*SubscribeOrderbookRequest, MarketData_SubscribeOrderbookServer) error
	mustEmbedUnimplementedMarketDataServer()
}

// UnimplementedMarketDataServer must be embedded to have forward compatible implementations.
type UnimplementedMarketDataServer struct {
}

func (UnimplementedMarketDataServer) GetCandles(context.Context, *GetCandlesRequest) (*GetCandlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCandles not implemented")
}
func (UnimplementedMarketDataServer) SubscribeCandles(*SubscribeCandlesRequest, MarketData_SubscribeCandlesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeCandles not implemented")
}
func (UnimplementedMarketDataServer) SubscribeOrders(*SubscribeOrderRequest, MarketData_SubscribeOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOrders not implemented")
}
func (UnimplementedMarketDataServer) SubscribeOrderbook(*SubscribeOrderbookRequest, MarketData_SubscribeOrderbookServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOrderbook not implemented")
}
func (UnimplementedMarketDataServer) mustEmbedUnimplementedMarketDataServer() {}

// UnsafeMarketDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServer will
// result in compilation errors.
type UnsafeMarketDataServer interface {
	mustEmbedUnimplementedMarketDataServer()
}

func RegisterMarketDataServer(s grpc.ServiceRegistrar, srv MarketDataServer) {
	s.RegisterService(&MarketData_ServiceDesc, srv)
}

func _MarketData_GetCandles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServer).GetCandles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketData_GetCandles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServer).GetCandles(ctx, req.(*GetCandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketData_SubscribeCandles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeCandlesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).SubscribeCandles(m, &marketDataSubscribeCandlesServer{stream})
}

type MarketData_SubscribeCandlesServer interface {
	Send(*OHLC) error
	grpc.ServerStream
}

type marketDataSubscribeCandlesServer struct {
	grpc.ServerStream
}

func (x *marketDataSubscribeCandlesServer) Send(m *OHLC) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketData_SubscribeOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).SubscribeOrders(m, &marketDataSubscribeOrdersServer{stream})
}

type MarketData_SubscribeOrdersServer interface {
	Send(*OrderState) error
	grpc.ServerStream
}

type marketDataSubscribeOrdersServer struct {
	grpc.ServerStream
}

func (x *marketDataSubscribeOrdersServer) Send(m *OrderState) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketData_SubscribeOrderbook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOrderbookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).SubscribeOrderbook(m, &marketDataSubscribeOrderbookServer{stream})
}

type MarketData_SubscribeOrderbookServer interface {
	Send(*Orderbook) error
	grpc.ServerStream
}

type marketDataSubscribeOrderbookServer struct {
	grpc.ServerStream
}

func (x *marketDataSubscribeOrderbookServer) Send(m *Orderbook) error {
	return x.ServerStream.SendMsg(m)
}

// MarketData_ServiceDesc is the grpc.ServiceDesc for MarketData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketData.MarketData",
	HandlerType: (*MarketDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCandles",
			Handler:    _MarketData_GetCandles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCandles",
			Handler:       _MarketData_SubscribeCandles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeOrders",
			Handler:       _MarketData_SubscribeOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeOrderbook",
			Handler:       _MarketData_SubscribeOrderbook_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "marketData.proto",
}
