export const ipcEvents = {
    REGISTER: 'REGISTER',
    GET_AUTH_INFO: 'GET_AUTH_INFO',
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    SET_ACCOUNT: 'SET_ACCOUNT',
    GET_CANDLES: 'GET_CANDLES',
    SUBSCRIBE_CANDLES: 'SUBSCRIBE_CANDLES',
    NEW_CANDLE: 'NEW_CANDLE',
}