export const ipcEvents = {
    TEST_HELLO: "TEST_HELLO",
    REGISTER: 'REGISTER',
    GET_AUTH_INFO: 'GET_AUTH_INFO',
    GET_ACCOUNTS: 'GET_ACCOUNTS',
    SET_ACCOUNT: 'SET_ACCOUNT',
    GET_SHARES: 'GET_SHARES',
    INIT_SDK: 'INIT_SDK',
}