// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: marketData.proto

package grpcGW_marketdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Что ждем от клиента
type GetCandlesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstrumentId string                 `protobuf:"bytes,1,opt,name=instrumentId,proto3" json:"instrumentId,omitempty"`
	Interval     int32                  `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Start        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *GetCandlesRequest) Reset() {
	*x = GetCandlesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesRequest) ProtoMessage() {}

func (x *GetCandlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesRequest.ProtoReflect.Descriptor instead.
func (*GetCandlesRequest) Descriptor() ([]byte, []int) {
	return file_marketData_proto_rawDescGZIP(), []int{0}
}

func (x *GetCandlesRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *GetCandlesRequest) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *GetCandlesRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetCandlesRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// Что хотим вернуть
type GetCandlesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candles []*GetCandlesResponse_OHLC `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
}

func (x *GetCandlesResponse) Reset() {
	*x = GetCandlesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesResponse) ProtoMessage() {}

func (x *GetCandlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesResponse.ProtoReflect.Descriptor instead.
func (*GetCandlesResponse) Descriptor() ([]byte, []int) {
	return file_marketData_proto_rawDescGZIP(), []int{1}
}

func (x *GetCandlesResponse) GetCandles() []*GetCandlesResponse_OHLC {
	if x != nil {
		return x.Candles
	}
	return nil
}

type GetCandlesResponse_Quant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units int32 `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	Nano  int32 `protobuf:"varint,2,opt,name=nano,proto3" json:"nano,omitempty"`
}

func (x *GetCandlesResponse_Quant) Reset() {
	*x = GetCandlesResponse_Quant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandlesResponse_Quant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesResponse_Quant) ProtoMessage() {}

func (x *GetCandlesResponse_Quant) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesResponse_Quant.ProtoReflect.Descriptor instead.
func (*GetCandlesResponse_Quant) Descriptor() ([]byte, []int) {
	return file_marketData_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetCandlesResponse_Quant) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *GetCandlesResponse_Quant) GetNano() int32 {
	if x != nil {
		return x.Nano
	}
	return 0
}

type GetCandlesResponse_OHLC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Open   *GetCandlesResponse_Quant `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	High   *GetCandlesResponse_Quant `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	Low    *GetCandlesResponse_Quant `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	Close  *GetCandlesResponse_Quant `protobuf:"bytes,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume int64                     `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Time   *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GetCandlesResponse_OHLC) Reset() {
	*x = GetCandlesResponse_OHLC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandlesResponse_OHLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandlesResponse_OHLC) ProtoMessage() {}

func (x *GetCandlesResponse_OHLC) ProtoReflect() protoreflect.Message {
	mi := &file_marketData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandlesResponse_OHLC.ProtoReflect.Descriptor instead.
func (*GetCandlesResponse_OHLC) Descriptor() ([]byte, []int) {
	return file_marketData_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetCandlesResponse_OHLC) GetOpen() *GetCandlesResponse_Quant {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *GetCandlesResponse_OHLC) GetHigh() *GetCandlesResponse_Quant {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *GetCandlesResponse_OHLC) GetLow() *GetCandlesResponse_Quant {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *GetCandlesResponse_OHLC) GetClose() *GetCandlesResponse_Quant {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *GetCandlesResponse_OHLC) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *GetCandlesResponse_OHLC) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_marketData_proto protoreflect.FileDescriptor

var file_marketData_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb3, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2c, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0xbf, 0x03, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x07,
	0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x48,
	0x4c, 0x43, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x1a, 0x31, 0x0a, 0x05, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x61, 0x6e, 0x6f, 0x1a, 0xb6,
	0x02, 0x0a, 0x04, 0x4f, 0x48, 0x4c, 0x43, 0x12, 0x38, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x04, 0x6f, 0x70, 0x65,
	0x6e, 0x12, 0x38, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x36, 0x0a, 0x03, 0x6c,
	0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x03,
	0x6c, 0x6f, 0x77, 0x12, 0x3a, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x59, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x47, 0x57, 0x2e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_marketData_proto_rawDescOnce sync.Once
	file_marketData_proto_rawDescData = file_marketData_proto_rawDesc
)

func file_marketData_proto_rawDescGZIP() []byte {
	file_marketData_proto_rawDescOnce.Do(func() {
		file_marketData_proto_rawDescData = protoimpl.X.CompressGZIP(file_marketData_proto_rawDescData)
	})
	return file_marketData_proto_rawDescData
}

var file_marketData_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketData_proto_goTypes = []interface{}{
	(*GetCandlesRequest)(nil),        // 0: marketData.GetCandlesRequest
	(*GetCandlesResponse)(nil),       // 1: marketData.GetCandlesResponse
	(*GetCandlesResponse_Quant)(nil), // 2: marketData.GetCandlesResponse.Quant
	(*GetCandlesResponse_OHLC)(nil),  // 3: marketData.GetCandlesResponse.OHLC
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_marketData_proto_depIdxs = []int32{
	4, // 0: marketData.GetCandlesRequest.start:type_name -> google.protobuf.Timestamp
	4, // 1: marketData.GetCandlesRequest.end:type_name -> google.protobuf.Timestamp
	3, // 2: marketData.GetCandlesResponse.candles:type_name -> marketData.GetCandlesResponse.OHLC
	2, // 3: marketData.GetCandlesResponse.OHLC.open:type_name -> marketData.GetCandlesResponse.Quant
	2, // 4: marketData.GetCandlesResponse.OHLC.high:type_name -> marketData.GetCandlesResponse.Quant
	2, // 5: marketData.GetCandlesResponse.OHLC.low:type_name -> marketData.GetCandlesResponse.Quant
	2, // 6: marketData.GetCandlesResponse.OHLC.close:type_name -> marketData.GetCandlesResponse.Quant
	4, // 7: marketData.GetCandlesResponse.OHLC.time:type_name -> google.protobuf.Timestamp
	0, // 8: marketData.MarketData.GetCandles:input_type -> marketData.GetCandlesRequest
	1, // 9: marketData.MarketData.GetCandles:output_type -> marketData.GetCandlesResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_marketData_proto_init() }
func file_marketData_proto_init() {
	if File_marketData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marketData_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandlesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketData_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandlesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketData_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandlesResponse_Quant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketData_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandlesResponse_OHLC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marketData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketData_proto_goTypes,
		DependencyIndexes: file_marketData_proto_depIdxs,
		MessageInfos:      file_marketData_proto_msgTypes,
	}.Build()
	File_marketData_proto = out.File
	file_marketData_proto_rawDesc = nil
	file_marketData_proto_goTypes = nil
	file_marketData_proto_depIdxs = nil
}
