name: Go
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Download Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          cd ./server && go get -v -t -d ./...

      - name: Build and run tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd ./server && go build .

      - name: Test
        run: cd ./server && go test -v ./...
